//组件数组
const componentArr = [
    {
        name: '输入字段',
        children: [
            {
                name: 'input',
                iconType: 'icondanhang',
                text: '单行文本框',
            }, 
            {
                name: 'textarea',
                iconType: 'iconduohangwenben',
                text: '多行文本框',
            }, 
            {
                name: 'number',
                iconType: 'iconjishuqi',
                text: '计数器',
            }, 
            {
                name: 'password',
                iconType: 'iconmima',
                text: '密码',
            }, 
            {
                name: 'link',
                iconType: 'iconchaolianjie',
                text: '超链接',
            }
        ]
    }, 
    {
        name: '选择字段',
        children: [
            {
                name: 'select',
                iconType: 'iconxialakuang',
                text: '下拉单选框',
            }, 
            {
                name: 'selectMultiple',
                iconType: 'iconxialakuang',
                text: '下拉多选框',
            },
            {
                name: 'radio',
                iconType: 'icondanxuanxuanzhong',
                text: '单选框组',
            }, 
            {
                name: 'checkbox',
                iconType: 'iconduoxuankuang1-copy',
                text: '多选框组',
            }, 
            {
                name: 'slider',
                iconType: 'iconscroll-bar',
                text: '滑动选择条',
            }, 
            // {
            //     name: 'switchs',
            //     iconType: 'iconguan-copy',
            //     text: '开关',
            // }, 
            {
                name: 'stars',
                iconType: 'iconpingfen',
                text: '评分',
            },
            {
                name: 'treeSelect',
                iconType: 'iconshuxingxuanzeqi',
                text: '树形选择器',
            },
            {
                name: 'cascader',
                iconType: 'iconjilianxuanze',
                text: '级联选择器',
            },
        ]
    }, 
    {
        name: '日期字段',
        children: [
            {
                name: 'dateYear',
                iconType: 'iconnian',
                text: '年选择器',
            },
            {
                name: 'dateMonth',
                iconType: 'iconyue',
                text: '月选择器',
            },
            {
                name: 'dateWeek',
                iconType: 'iconzhou',
                text: '周选择器',
            },
            {
                name: 'date',
                iconType: 'iconriqixuanze',
                text: '日期选择器',
            },
            {
                name: 'dateTime',
                iconType: 'iconshijian',
                text: '时间选择器',
            },
            {
                name: 'dateAndTime',
                iconType: 'iconriqishijian',
                text: '日期时间',
            },
            {
                name: 'dateRange',
                iconType: 'iconriqifanwei',
                text: '日期范围',
            },
            {
                name: 'dateTimeRange',
                iconType: 'iconshijianfanwei',
                text: '时间范围',
            },
            {
                name: 'dateAndTimeRange',
                iconType: 'iconriqishijianfanwei',
                text: '日期时间范围',
            },
        ]
    },
    {
        name: '布局字段',
        children: [
            {
                name: 'mainTitle',
                iconType: 'iconriqixuanze',
                text: '标题',
            },
            // {
            //     name: 'groupArea',
            //     iconType: 'iconfenzu',
            //     text: '分组',
            // },
        ]
    },
]

//组件属性
const componentItem = {
    input: {
        type: 'input',
        placeholder: '请输入',
        label: '单行文本',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        prefix: '',
        suffix: '',
        maxLength: 1000,
        required: false,
        requiredText: '',
    },
    textarea: {
        type: 'textarea',
        placeholder: '请输入',
        label: '多行文本',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        showCount: false,
        showCountText: '',
        maxLength: 1000,
        required: false,
        requiredText: '',
    },
    select: {
        type: 'select',
        placeholder: '请选择',
        label: '下拉单选',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: true,
        requiredText: 'true',
        showSearch: false,
        showSearchText: '',
        optionArr: ['选项1'],
    },
    selectMultiple: {
        type: 'selectMultiple',
        placeholder: '请选择',
        label: '下拉多选',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
        showSearch: false,
        showSearchText: '',
        optionArr: ['选项1'],
        mode: 'multiple',
    },
    number: {
        type: 'number',
        label: '计数器',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: true,
        requiredText: 'true',
        min: 0,
        max: 100,
        step: 1,
    },
    radio: {
        type: 'radio',
        label: '单选框组',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: true,
        requiredText: 'true',
        optionArr: ['选项1'],
    },
    checkbox: {
        type: 'checkbox',
        label: '多选框组',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
        optionArr: ['选项1'],
    },
    date: {
        type: 'date',
        placeholder: '请选择日期',
        label: '日期选择器',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateYear: {
        type: 'dateYear',
        placeholder: '请选择年份',
        label: '年选择器',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateMonth: {
        type: 'dateMonth',
        placeholder: '请选择月份',
        label: '月选择器',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateWeek: {
        type: 'dateWeek',
        placeholder: '请选择周',
        label: '周选择器',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateTime: {
        type: 'dateTime',
        placeholder: '请选择时间',
        label: '时间选择器',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateAndTime: {
        type: 'dateAndTime',
        placeholder: '请选择日期时间',
        label: '日期时间',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateRange: {
        type: 'dateRange',
        label: '日期范围',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateTimeRange: {
        type: 'dateTimeRange',
        label: '时间范围',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    dateAndTimeRange: {
        type: 'dateAndTimeRange',
        label: '日期时间范围',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
    },
    password: {
        type: 'password',
        placeholder: '请输入',
        label: '密码',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        prefix: '',
        suffix: '',
        maxLength: 1000,
        required: false,
        requiredText: '',
    },
    group: {
        type: 'group',
    },
    slider: {
        type: 'slider',
        label: '滑动选择',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
        min: 0,
        max: 100,
        unit: '%',
    },
    switchs: {
        type: 'switchs',
        label: '开关',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        required: false,
        requiredText: '',
        checkedChildren: '开启',
        unCheckedChildren: '关闭',
    },
    stars: {
        type: 'stars',
        label: '评分',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        required: false,
        requiredText: '',
        character: '',
    },
    link: {
        type: 'link',
        label: '超链接',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        required: false,
        requiredText: '',
        hoverLinkUrl: '',
        hoverLinkText: '链接地址',
    },
    mainTitle: {
        type: 'mainTitle',
        label: '标题',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
    },
    groupArea: {
        type: 'groupArea',
        label: '分组',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
    },
    treeSelect: {
        type: 'treeSelect',
        placeholder: '请选择',
        label: '树形选择',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
        showSearch: false,
        showSearchText: '',
        multiple: false,
        multipleText: '',
        treeData: [
            {
                title: '选项1', 
                key: 1, 
                value: 1,
                readOnly: true,
                level: 1,
                label: '选项1', 
            },
        ],
        expandedRowKeys: [1],
    },
    cascader: {
        type: 'cascader',
        placeholder: '请选择',
        label: '级联选择',
        labelWidth: 120,
        labelSuffix: '：',
        labelAlign: 'left',
        labelAlignText: 'left',
        width: 24,
        required: false,
        requiredText: '',
        showSearch: false,
        showSearchText: '',
        treeData: [
            {
                title: '选项1', 
                key: 1, 
                value: 1,
                readOnly: true,
                level: 1,
                label: '选项1', 
            },
        ],
        expandedRowKeys: [1],
    },
}

export {
    componentArr,
    componentItem,
}